[models.providers.oai]
baseUrl = "http://localhost:11434/v1"
apiKey = "api-key"

[[models.providers.oai.models]]
id = "qwen3.5:35b-a3b-q8_0"
name = "qwen3.5-35b"
input = ["text", "image"]
contextWindow = 32768
maxTokens = 8192

[agents.defaults]
timeoutSeconds = 600
maxConcurrent = 1

[agents.defaults.subagents]
maxConcurrent = 1

[channels.discord]
token = "DISCORD_BOT_TOKEN"
server_id = "1234"
approval_user_id = "YOUR_DISCORD_USER_ID"
